// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVWWv46muRCBAoH8a-oacQ3zMWCU6fqM',
    appId: '1:436047744269:web:b25e59dd50e4336c09b444',
    messagingSenderId: '436047744269',
    projectId: 'indoor-navigation-app-cfb2f',
    authDomain: 'indoor-navigation-app-cfb2f.firebaseapp.com',
    storageBucket: 'indoor-navigation-app-cfb2f.firebasestorage.app',
    measurementId: 'G-DC2PVP4BPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsey1dLwzaFLcKdtiHos6r-lDiqkvzLw',
    appId: '1:436047744269:android:cecd53db72e3ee6609b444',
    messagingSenderId: '436047744269',
    projectId: 'indoor-navigation-app-cfb2f',
    storageBucket: 'indoor-navigation-app-cfb2f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdVWWv46muRCBAoH8a-oacQ3zMWCU6fqM',
    appId: '1:436047744269:web:e4f03e2fbca253fa09b444',
    messagingSenderId: '436047744269',
    projectId: 'indoor-navigation-app-cfb2f',
    authDomain: 'indoor-navigation-app-cfb2f.firebaseapp.com',
    storageBucket: 'indoor-navigation-app-cfb2f.firebasestorage.app',
    measurementId: 'G-GPHZW1VY2K',
  );
}
